### PR TITLE
Integrated Vuejs

### PR DESCRIPTION
**Pull request by AdoraNwodo**
Refer to [figma](https://www.figma.com/file/DDNorOpAze0UU5IEVic4Qf4c/Untitled?node-id=1%3A13), although I added one more page to show full results.

### Pages
1. Home - List of all the candidates running
2. WhyVote - Page showing a single candidate with a user should fill stating why they would vote for them.
3. Results - Total result. Shows the total number of votes and the percentage of vote per candidate.
4. Opinions - List of people's opinions (Reasons why they would vote a candidate. Everyone is kept anonymous).

### CODE REVIEW

**Comment by iamfunsho** [comment]
I don't think we should make everyone anonymous. It defeats making that section relatable. If a user chooses to not be anonymous, let's show their name. This is already taken care of in the API

**Comment by iamfunsho** [comment]
I have some design issues, but let's keep it at operational level for now

**Comment by iamfunsho** [comment]
Also, can you add lazy loading to the people's opinion, such that as users scroll, more opinions are loaded in the background.

**Comment by AdoraNwodo** [comment]
@iamfunsho Okay then. would keep the anonymity in mind when I integrate the API. What design issues?

**Comment by AdoraNwodo** [comment]
@iamfunsho I was actually thinking pagination. Thoughts?

**Comment by iamfunsho** [comment]
> @iamfunsho Okay then. would keep the anonymity in mind when I integrate the API. What design issues?

For now, on mobile, can we display two candidates on a row, that way, users don't get to scroll for too long looking for their candidates?

**Comment by iamfunsho** [comment]
> @iamfunsho I was actually thinking pagination. Thoughts?

Pagination requires users clicking and waiting for data/content to load, however, with scroll-based loading, they don't have to click and wait. 

From my experience, we can keep users more engaged on the page with this.

**Comment by AdoraNwodo** [comment]
Okay, you have a point. I'd fix the pagination and the number of candidates on a row on mobile.

**Comment by iamfunsho** [comment]
> Okay, you have a point. I'd fix the pagination and the number of candidates on a row on mobile.

Do you want to make that a new branch and create a pull request? Or still this PR?

**Comment by AdoraNwodo** [comment]
> > Okay, you have a point. I'd fix the pagination and the number of candidates on a row on mobile.
> 
> Do you want to make that a new branch and create a pull request? Or still this PR?

Still this PR. I'd make my commits here.

**Comment by AdoraNwodo** [comment]
This new commit includes:
     `Endless scrolling to people's opinion`
     `Social media share buttons`
     `Image download button`
     `Total results` 
     `Images & Social media posts of candidates`
     `Integration with live API.`


How to upload:
1. Clone locally
2. run `npm install`
3. run `npm run build`
4. Upload the `/dist` directory to the server

**Comment by iamfunsho** [comment]
This commit still uses placeholders, also, I can't find the candidate images in the `asset` folder
Also, it doesn't point to the API service online, it is still using `localhost:8002`.

**Comment by AdoraNwodo** [comment]
> This commit still uses placeholders, also, I can't find the candidate images in the `asset` folder
> Also, it doesn't point to the API service online, it is still using `localhost:8002`.

Hmm. I think you should pull again and check this properly

**Pull request merged**
